### ISSUE TITLE
Dead link: eidentita.cz

### ISSUE THREAD

**Issue by prochac** [SemaiCZE/eop-docker#2]
Stat pustil domenu, a nekdo na to navesil affiliate redirecty
eidentita.cz

**Comment by SemaiCZE** [comment]
Dnes v dobach MojeID a BankID uz tento repozitar nedava uplne smysl. Dopsal jsem [komentar do readme](https://github.com/SemaiCZE/eop-docker/commit/eddd2f8687cb5b27fccd7925d381852fa5b78207) a projekt archivuji.
